server:
  port: 8085
  
spring:
  application:
    name: CONFIG-SERVER
 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rohanjaiswal1904/MicroservicesConfig.git
          clone-on-start: true